[source]

=== CSS Basic Layout

CSS provides various techniques to control the layout of HTML elements on a page=== Here are some basic layout concepts:

=== Float

The float property is used to float an element to the left or right side of its container, allowing other elements to wrap around it Example:
[source,css]
img {
float: right;
}

=== Display Block

A block-level element starts on a new line and takes up the full width available Examples of block-level elements include <div>, <h1>-<h6>, and <p> To set an element as a block-level element, use the display property:
[source,css]
span {
display: block;
}

=== Display Inline

Inline elements do not start on a new line and only take up as much width as necessary=== Examples of inline elements include <span>, <a>, and <img> To set an element as an inline element, use the display property:
[source,css]
div {
display: inline;
}

=== Display inline-block

The display: inline-block property combines the features of both inline and block elements An inline-block element behaves like an inline element, but it can have a width, height, padding, and margin like a block-level element Example:
[source,css]
div {
display: inline-block;
}

=== Wrapper Container, Fluid Container

A wrapper container is an element that wraps around other elements to provide a specific layout, while a fluid container adjusts its width based on the size of the viewport (browser window) Example:
[source,css]

.wrapper {
width: 960px;
margin: 0 auto;
}
.fluid-container {
width: 100%;
padding: 0 15px;
}

=== Padding

The padding property is used to create space around an element's content, inside its border=== Example:
[source,css]
div {
padding: 10px;
}

=== Margin

The margin property is used to create space around an element's border, outside of any defined padding Example:
[source,css]
div {
margin: 10px;
}

=== Border-box Model

The box-sizing property with the border-box value is used to include the padding and border within the element's specified width and height, preventing the element from expanding due to padding and border size Example:
[source,css]
div {
box-sizing: border-box;
}


== Excercises:
. Building store homepage with following details:
.. layout for 2 column website including sidebar, content-bar and header and footer
.. 12 product in 3-column view in content-bar.
.. Each product holds a summary of the product data: e.g. description, price, stock

. Product Detail page:
.. with picture and description of the product in the content-bar
.. Make sure a customer can click on a product on the product overview page
.. Make sure the customer is redirected to a product details page
.. Place the picture left, details right and transport details below
.. Create a button; add to cart (the button doesn't have to do anything, but it should be clickable)