
== HTML Basics E2

=== Div
The `<div>` tag is used to group together other HTML elements into a container. It is commonly used for layout and to apply styles to a group of elements. For example:

[source,html]
----
<div>
  <p>This is some text.</p>
  <p>This is some more text.</p>
</div>
----

=== Links & Anchors:
To create a hyperlink in HTML, use the <a> tag. The href attribute specifies the URL of the page you want to link to. For example:



[source,html]
----
<a href="http://www.example.com">Link Text</a>
----

To link to a specific section of a page, use an anchor. An anchor is created using the <a> tag with the name attribute set to the name of the anchor. For example:


[source,html]
----
<a name="section1"></a>
<h2>Section 1</h2>
<p>This is the content of section 1.</p>
----

You can then link to the anchor using the # symbol followed by the name of the anchor. For example:



[source,html]
----
<a href="#section1">Link to Section 1</a>
----


=== Lists:
There are two main types of lists in HTML: ordered lists and unordered lists.

Ordered lists use the <ol> tag and list items are marked with the <li> tag. For example:


[source,html]
----
<ol>
  <li>Item 1</li>
  <li>Item 2</li>
  <li>Item 3</li>
</ol>
----

Unordered lists use the <ul> tag and list items are marked with the <li> tag. For example:


[source,html]
----
<ul>
  <li>Item 1</li>
  <li>Item 2</li>
  <li>Item 3</li>
</ul>
----

You can also create nested lists by placing one list inside another.